/**
 * Recommended foreground and background pairs.
 *
 * Text pairs must reach 4.5:1 and non-text indicators 3:1 in both modes. The
 * documentation measures these values with `src/lib/contrast.ts`, and
 * `pnpm --filter @dicehub/kappa-docs-astro test:markdown` fails when a pair
 * drops below its minimum. Decorative boundaries and disabled surfaces stay
 * out of this list on purpose.
 *
 * read_when: you retune a token value or add a pair worth publishing.
 */

import type { ThemeContrastPair } from "./types.ts";

export const themeContrastPairs: ThemeContrastPair[] = [
  {
    id: "text-default-on-canvas",
    label: "Default text on canvas",
    foreground: "--kappa-default",
    background: "--kappa-canvas",
    kind: "text",
    minimum: 4.5,
    note: "Primary reading pair for page-level copy.",
  },
  {
    id: "text-default-on-control",
    label: "Default text on controls",
    foreground: "--kappa-default",
    background: "--kappa-control",
    kind: "text",
    minimum: 4.5,
    note: "Inputs, buttons, and menu labels.",
  },
  {
    id: "text-default-on-tint",
    label: "Default text on tint",
    foreground: "--kappa-default",
    background: "--kappa-tint",
    kind: "text",
    minimum: 4.5,
    note: "Copy inside recessed panels and grouped rows.",
  },
  {
    id: "text-strong-on-base",
    label: "Strong text on base",
    foreground: "--kappa-strong",
    background: "--kappa-base",
    kind: "text",
    minimum: 4.5,
    note: "Headings and emphasized values on raised surfaces.",
  },
  {
    id: "text-subtle-on-tint",
    label: "Supporting text on tint",
    foreground: "--kappa-subtle",
    background: "--kappa-tint",
    kind: "text",
    minimum: 4.5,
    note: "The pair that set the light supporting-text value.",
  },
  {
    id: "text-subtle-on-overlay",
    label: "Supporting text on overlay",
    foreground: "--kappa-subtle",
    background: "--kappa-overlay",
    kind: "text",
    minimum: 4.5,
    note: "Labels that sit on hover and overlay fills.",
  },
  {
    id: "text-muted-on-control",
    label: "Placeholder text on controls",
    foreground: "--kappa-muted",
    background: "--kappa-control",
    kind: "text",
    minimum: 4.5,
    note: "Placeholders and empty-state copy in fields.",
  },
  {
    id: "accent-text-on-control",
    label: "Accent text on controls",
    foreground: "--kappa-accent",
    background: "--kappa-control",
    kind: "text",
    minimum: 4.5,
    note: "Links, selected indicators, and accent labels.",
  },
  {
    id: "accent-contrast-on-accent-solid",
    label: "Text on solid accent",
    foreground: "--kappa-accent-contrast",
    background: "--kappa-accent-solid",
    kind: "text",
    minimum: 4.5,
    note: "Primary action and checked-control label pair.",
  },
  {
    id: "selected-contrast-on-selected-background",
    label: "Text on selection fill",
    foreground: "--kappa-selected-contrast",
    background: "--kappa-selected-background",
    kind: "text",
    minimum: 4.5,
    note: "Pressed toolbar buttons and selected calendar days.",
  },
  {
    id: "selected-text-on-canvas",
    label: "Selected text on canvas",
    foreground: "--kappa-selected-text",
    background: "--kappa-canvas",
    kind: "text",
    minimum: 4.5,
    note: "Checked options that mark selection with text alone.",
  },
  {
    id: "info-text-on-info-tint",
    label: "Info text on info tint",
    foreground: "--kappa-info-text",
    background: "--kappa-info-tint",
    kind: "text",
    minimum: 4.5,
    note: "Informational banners and status badges.",
  },
  {
    id: "success-text-on-success-tint",
    label: "Success text on success tint",
    foreground: "--kappa-success-text",
    background: "--kappa-success-tint",
    kind: "text",
    minimum: 4.5,
    note: "Success banners and status badges.",
  },
  {
    id: "warning-text-on-warning-tint",
    label: "Warning text on warning tint",
    foreground: "--kappa-warning-text",
    background: "--kappa-warning-tint",
    kind: "text",
    minimum: 4.5,
    note: "Warning banners and status badges.",
  },
  {
    id: "danger-text-on-danger-tint",
    label: "Danger text on danger tint",
    foreground: "--kappa-danger-text",
    background: "--kappa-danger-tint",
    kind: "text",
    minimum: 4.5,
    note: "Error banners, invalid fields, and status badges.",
  },
  {
    id: "accent-contrast-on-info-solid",
    label: "Label on solid info",
    foreground: "--kappa-accent-contrast",
    background: "--kappa-info-solid",
    kind: "text",
    minimum: 4.5,
    note: "Notice actions that fill with the informational solid.",
  },
  {
    id: "accent-contrast-on-success-solid",
    label: "Label on solid success",
    foreground: "--kappa-accent-contrast",
    background: "--kappa-success-solid",
    kind: "text",
    minimum: 4.5,
    note: "Confirmation actions that fill with the success solid.",
  },
  {
    id: "accent-contrast-on-warning-solid",
    label: "Label on solid warning",
    foreground: "--kappa-accent-contrast",
    background: "--kappa-warning-solid",
    kind: "text",
    minimum: 4.5,
    note: "Caution actions that fill with the warning solid.",
  },
  {
    id: "accent-contrast-on-danger-solid",
    label: "Label on solid danger",
    foreground: "--kappa-accent-contrast",
    background: "--kappa-danger-solid",
    kind: "text",
    minimum: 4.5,
    note: "Destructive actions that fill with the danger solid.",
  },
  {
    id: "focus-on-control",
    label: "Focus ring on controls",
    foreground: "--kappa-focus",
    background: "--kappa-control",
    kind: "nontext",
    minimum: 3,
    note: "Keyboard focus around inputs, buttons, and option rows.",
  },
  {
    id: "focus-on-canvas",
    label: "Focus ring on canvas",
    foreground: "--kappa-focus",
    background: "--kappa-canvas",
    kind: "nontext",
    minimum: 3,
    note: "Keyboard focus on page-level surfaces.",
  },
  {
    id: "selection-fill-on-base",
    label: "Selection fill on base",
    foreground: "--kappa-selected-background",
    background: "--kappa-base",
    kind: "nontext",
    minimum: 3,
    note: "Selected fill against the surface it replaces.",
  },
  {
    id: "danger-indicator-on-control",
    label: "Danger indicator on controls",
    foreground: "--kappa-danger",
    background: "--kappa-control",
    kind: "nontext",
    minimum: 3,
    note: "Invalid border and error indicator on fields.",
  },
];
