/**
 * Every published semantic color token with its light and dark values.
 *
 * read_when: you add, rename, or retune a token, or you need the documented
 * purpose and compatibility notes for one.
 */

import type { ThemeToken } from "./types.ts";

export const themeTokens: ThemeToken[] = [
  // Surfaces
  {
    name: "--kappa-canvas",
    group: "surfaces",
    description: "Application page background behind every surface.",
    light: "#fafafa",
    dark: "#030303",
    preview: "background",
  },
  {
    name: "--kappa-base",
    group: "surfaces",
    description: "Base panel surface for cards, popovers, and raised regions.",
    light: "#ffffff",
    dark: "#0f0f0f",
    preview: "background",
    compatibility: "Previously undefined, so components fell back to #ffffff in both modes.",
  },
  {
    name: "--kappa-control",
    group: "surfaces",
    description: "Interactive control surface for inputs, buttons, and menus.",
    light: "#ffffff",
    dark: "#18181b",
    preview: "background",
  },
  {
    name: "--kappa-tint",
    group: "surfaces",
    description: "Recessed surface for grouped rows, tracks, and low-emphasis fills.",
    light: "#f2f3f5",
    dark: "#262626",
    preview: "background",
  },
  {
    name: "--kappa-overlay",
    group: "surfaces",
    description: "Hover and overlay fill for rows, options, and quiet controls.",
    light: "#e9ebef",
    dark: "#303034",
    preview: "background",
  },
  {
    name: "--kappa-disabled-surface",
    group: "surfaces",
    description: "Fill for disabled inputs and disabled previews.",
    light: "var(--kappa-tint)",
    dark: "var(--kappa-tint)",
    preview: "background",
    compatibility: "Aliases --kappa-tint. Disabled text is exempt from contrast minimums.",
  },
  {
    name: "--kappa-readonly-surface",
    group: "surfaces",
    description: "Fill for read-only fields that stay focusable.",
    light: "var(--kappa-tint)",
    dark: "var(--kappa-tint)",
    preview: "background",
    compatibility: "Aliases --kappa-tint.",
  },

  // Text
  {
    name: "--kappa-default",
    group: "text",
    description: "Default body and control text.",
    light: "#171717",
    dark: "#f5f5f5",
    preview: "text",
  },
  {
    name: "--kappa-strong",
    group: "text",
    description: "Highest-emphasis headings, values, and selected labels.",
    light: "#0a0a0a",
    dark: "#fafafa",
    preview: "text",
    compatibility: "Previously provided by the documentation shell as --docs-strong.",
  },
  {
    name: "--kappa-subtle",
    group: "text",
    description: "Supporting text, labels, and icons.",
    light: "#696969",
    dark: "#a1a1a1",
    preview: "text",
    compatibility:
      "Light value corrected from #737373 (4.27:1 on tint) to #696969 (4.95:1 on tint).",
  },
  {
    name: "--kappa-muted",
    group: "text",
    description: "Placeholders and inactive copy.",
    light: "var(--kappa-subtle)",
    dark: "var(--kappa-subtle)",
    preview: "text",
    compatibility: "Aliases --kappa-subtle so placeholders move with supporting text.",
  },

  // Accent
  {
    name: "--kappa-accent",
    group: "accent",
    description: "Accent text, links, and selected indicators.",
    light: "#2479b6",
    dark: "#7185ff",
    preview: "text",
  },
  {
    name: "--kappa-accent-solid",
    group: "accent",
    description: "Solid accent fill for primary actions and checked controls.",
    light: "#247ab7",
    dark: "#247ab7",
    preview: "background",
  },
  {
    name: "--kappa-accent-contrast",
    group: "accent",
    description: "Text and icons placed on --kappa-accent-solid.",
    light: "#ffffff",
    dark: "#ffffff",
    preview: "text",
  },

  // Selection
  {
    name: "--kappa-selected-background",
    group: "selection",
    description: "Fill for selected items that invert to a strong surface.",
    light: "#0a0a0a",
    dark: "#fafafa",
    preview: "background",
    compatibility: "Takes the fill role of the deprecated --kappa-selected.",
  },
  {
    name: "--kappa-selected-contrast",
    group: "selection",
    description: "Text and icons placed on --kappa-selected-background.",
    light: "#ffffff",
    dark: "#0f0f0f",
    preview: "text",
    compatibility: "Required whenever you keep a --kappa-selected override.",
  },
  {
    name: "--kappa-selected-text",
    group: "selection",
    description: "Selected text on an unchanged surface, without a fill.",
    light: "var(--kappa-strong)",
    dark: "var(--kappa-strong)",
    preview: "text",
    compatibility: "Takes the text role of the deprecated --kappa-selected.",
  },

  // Status
  {
    name: "--kappa-info",
    group: "status",
    description: "Informational border and indicator color.",
    light: "#175cd3",
    dark: "#175cd3",
    preview: "background",
    compatibility: "Matches --kappa-info-solid.",
  },
  {
    name: "--kappa-info-text",
    group: "status",
    description: "Informational text and icons on tint or surface fills.",
    light: "#175cd3",
    dark: "#93c5fd",
    preview: "text",
  },
  {
    name: "--kappa-info-solid",
    group: "status",
    description: "Solid informational fill for banners and notice actions.",
    light: "#175cd3",
    dark: "#175cd3",
    preview: "background",
  },
  {
    name: "--kappa-info-tint",
    group: "status",
    description: "Informational tinted surface.",
    light: "#dbeafe",
    dark: "#10233f",
    preview: "background",
  },
  {
    name: "--kappa-success",
    group: "status",
    description: "Success border and completion indicator.",
    light: "#027a48",
    dark: "#027a48",
    preview: "background",
    compatibility: "Matches --kappa-success-solid; used by Input OTP completion.",
  },
  {
    name: "--kappa-success-text",
    group: "status",
    description: "Success text and icons on tint or surface fills.",
    light: "#027a48",
    dark: "#86efac",
    preview: "text",
  },
  {
    name: "--kappa-success-solid",
    group: "status",
    description: "Solid success fill for confirmations and actions.",
    light: "#027a48",
    dark: "#027a48",
    preview: "background",
  },
  {
    name: "--kappa-success-tint",
    group: "status",
    description: "Success tinted surface.",
    light: "#d1fadf",
    dark: "#102f20",
    preview: "background",
  },
  {
    name: "--kappa-warning",
    group: "status",
    description: "Warning border and indicator color.",
    light: "#b54708",
    dark: "#b54708",
    preview: "background",
    compatibility: "Matches --kappa-warning-solid.",
  },
  {
    name: "--kappa-warning-text",
    group: "status",
    description: "Warning text and icons on tint or surface fills.",
    light: "#b54708",
    dark: "#fde68a",
    preview: "text",
  },
  {
    name: "--kappa-warning-solid",
    group: "status",
    description: "Solid warning fill for alerts and caution actions.",
    light: "#b54708",
    dark: "#b54708",
    preview: "background",
  },
  {
    name: "--kappa-warning-tint",
    group: "status",
    description: "Warning tinted surface.",
    light: "#fef0c7",
    dark: "#3b2f10",
    preview: "background",
  },
  {
    name: "--kappa-danger",
    group: "status",
    description: "Danger border and invalid-state indicator.",
    light: "#b42318",
    dark: "#f87171",
    preview: "background",
    compatibility:
      "Matches --kappa-danger-solid in light mode; the dark indicator is raised for field borders.",
  },
  {
    name: "--kappa-danger-text",
    group: "status",
    description: "Danger text and icons on tint or surface fills.",
    light: "#b42318",
    dark: "#fca5a5",
    preview: "text",
  },
  {
    name: "--kappa-danger-solid",
    group: "status",
    description: "Solid danger fill for destructive actions.",
    light: "#b42318",
    dark: "#b42318",
    preview: "background",
  },
  {
    name: "--kappa-danger-tint",
    group: "status",
    description: "Danger tinted surface.",
    light: "#fee4e2",
    dark: "#3b1716",
    preview: "background",
  },

  // Charts
  {
    name: "--kappa-chart-1",
    group: "charts",
    description: "First chart series and primary data emphasis.",
    light: "#247ab7",
    dark: "#8292ff",
    preview: "background",
  },
  {
    name: "--kappa-chart-2",
    group: "charts",
    description: "Second chart series.",
    light: "#087f8c",
    dark: "#4cc4d0",
    preview: "background",
  },
  {
    name: "--kappa-chart-3",
    group: "charts",
    description: "Third chart series.",
    light: "#bb5a15",
    dark: "#f4a261",
    preview: "background",
  },
  {
    name: "--kappa-chart-4",
    group: "charts",
    description: "Fourth chart series.",
    light: "#337a4b",
    dark: "#70c58a",
    preview: "background",
  },
  {
    name: "--kappa-chart-5",
    group: "charts",
    description: "Fifth chart series.",
    light: "#9f3f75",
    dark: "#e084b4",
    preview: "background",
  },
  {
    name: "--kappa-chart-6",
    group: "charts",
    description: "Sixth chart series.",
    light: "#684bb6",
    dark: "#a78bfa",
    preview: "background",
  },
  {
    name: "--kappa-chart-7",
    group: "charts",
    description: "Seventh chart series.",
    light: "#ae3d39",
    dark: "#f3837e",
    preview: "background",
  },
  {
    name: "--kappa-chart-8",
    group: "charts",
    description: "Eighth chart series.",
    light: "#596579",
    dark: "#aeb6c3",
    preview: "background",
  },

  // Borders and focus
  {
    name: "--kappa-hairline",
    group: "border",
    description: "Subtle inner edge for nested separators and dividers.",
    light: "#e7eaef",
    dark: "#262626",
    preview: "background",
    compatibility: "Decorative boundary; not held to a contrast minimum.",
  },
  {
    name: "--kappa-line",
    group: "border",
    description: "Standard border for controls, cards, and layout separators.",
    light: "#e7eaef",
    dark: "#262626",
    preview: "background",
    compatibility: "Decorative boundary; not held to a contrast minimum.",
  },
  {
    name: "--kappa-input-border",
    group: "border",
    description: "Resting border for text inputs and field controls.",
    light: "#dcdcdc",
    dark: "#52525b",
    preview: "background",
    compatibility: "Decorative boundary; interactive hover and focus use --kappa-focus.",
  },
  {
    name: "--kappa-line-strong",
    group: "border",
    description: "Decorative boundary that is stronger than the hairline: grips, keycaps, and scrollbar thumbs.",
    light: "#c7cdd6",
    dark: "#52525b",
    preview: "background",
    compatibility:
      "Decorative only: 1.60:1 on light controls and 2.29:1 on dark controls. When a boundary must convey essential state, use --kappa-strong or --kappa-focus, or pair it with a fill. Dark value added by the theme.",
  },
  {
    name: "--kappa-focus",
    group: "border",
    description: "Focus ring color for keyboard focus.",
    light: "#247ab7",
    dark: "#247ab7",
    preview: "background",
  },
  {
    name: "--kappa-focus-soft",
    group: "border",
    description: "Translucent halo behind focus rings and selected text.",
    light: "rgba(36, 122, 183, 0.2)",
    dark: "#247ab73d",
    preview: "background",
    compatibility: "20% alpha in light mode, 24% in dark mode.",
  },

  // Supporting
  {
    name: "--kappa-shadow",
    group: "supporting",
    description: "Resting elevation for raised surfaces; removed in dark mode.",
    light: "0 1px 2px rgba(16, 24, 40, 0.05)",
    dark: "none",
    preview: "shadow",
  },
  {
    name: "--kappa-popover-shadow",
    group: "supporting",
    description: "Elevation for popovers, menus, and floating panels.",
    light: "0 8px 24px -6px rgba(16, 24, 40, 0.12), 0 2px 4px -2px rgba(16, 24, 40, 0.06)",
    dark: "0 16px 40px -12px rgba(0, 0, 0, 0.72)",
    preview: "shadow",
  },
  {
    name: "--kappa-emphasis",
    group: "supporting",
    description: "Neutral mix color for pressed overlays; not a text color.",
    light: "#17191f",
    dark: "#17191f",
    preview: "background",
    compatibility: "Color mixing only; use --kappa-strong for emphasized text.",
  },
  {
    name: "--kappa-badge-beta",
    group: "supporting",
    description: "Beta badge outline color for the Badge component.",
    light: "var(--kappa-accent)",
    dark: "var(--kappa-accent)",
    preview: "background",
    compatibility: "Aliases --kappa-accent.",
  },
  {
    name: "--kappa-badge-inverted",
    group: "supporting",
    description: "Inverted badge fill for the Badge component.",
    light: "var(--kappa-strong)",
    dark: "var(--kappa-strong)",
    preview: "background",
    compatibility: "Aliases --kappa-strong.",
  },
  {
    name: "--kappa-badge-inverted-contrast",
    group: "supporting",
    description: "Inverted badge label color for the Badge component.",
    light: "var(--kappa-base)",
    dark: "var(--kappa-base)",
    preview: "background",
    compatibility: "Aliases --kappa-base.",
  },
  {
    name: "--kappa-banner-focus",
    group: "supporting",
    description: "Focus ring used inside Banner surfaces.",
    light: "#247ab7",
    dark: "#93c5fd",
    preview: "background",
    compatibility:
      "Light mode matches --kappa-focus; dark mode raises to a lighter blue on banner tints.",
  },
];
