import { expect, test } from "@playwright/test";

test("Escape dismisses a peek, restores hidden-link focus, and respects nested popups", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/docs/components/sidebar");
  const demo = page.locator('[data-sidebar-demo="peeking"]');
  await expect.poll(() => demo.evaluate(el => el.closest("astro-island")?.hasAttribute("ssr"))).toBe(false);
  const nav = demo.getByRole("navigation");
  const outside = demo.locator('.sidebar-demo__topbar [data-slot="sidebar-trigger"]');
  const overview = nav.getByRole("link", { name: "Overview", exact: true });
  await demo.scrollIntoViewIfNeeded();
  await outside.focus();
  const box = await overview.boundingBox();
  const scrollBefore = await page.evaluate(() => window.scrollY);
  await page.mouse.move(box!.x + 10, box!.y + box!.height / 2);
  await expect(nav).toHaveAttribute("data-state", "peeking");
  expect(await page.evaluate(() => window.scrollY)).toBe(scrollBefore);
  await page.keyboard.press("Escape");
  await expect(nav).toHaveAttribute("data-state", "collapsed");
  await expect(outside).toBeFocused();
  await outside.hover();
  await overview.focus();
  await expect(nav).toHaveAttribute("data-state", "peeking");
  await nav.getByRole("link", { name: "Geometry", exact: true }).focus();
  await page.keyboard.press("Escape");
  await expect(nav).toHaveAttribute("data-state", "collapsed");
  await expect(nav.getByRole("button", { name: "Mesh", exact: true })).toBeFocused();
  await outside.focus();
  await nav.getByRole("button", { name: "Namespace: Engineering" }).focus();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("menu", { name: "Namespace: Engineering", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(nav).toHaveAttribute("data-state", "peeking");
  await page.keyboard.press("Escape");
  await expect(nav).toHaveAttribute("data-state", "collapsed");
  await outside.hover();
  await outside.focus();
  await overview.focus();
  await nav.getByRole("button", { name: "Quick search …" }).click();
  const palette = page.getByRole("dialog", { name: "Search navigation", exact: true });
  await expect(palette).toBeVisible();
  await palette.getByRole("combobox").press("Escape");
  await expect(palette).toBeHidden();
});
