import {
  DROPDOWN_DEFAULT_ITEM_VARIANT,
  DROPDOWN_DEFAULT_POSITIONING,
  DROPDOWN_ITEM_VARIANTS,
  isDropdownItemVariant,
  resolveDropdownItemVariant,
} from "../dropdown/dropdown";
import type { DropdownPositioningOptions } from "../dropdown/dropdown";

export const CONTEXT_MENU_ITEM_VARIANTS = DROPDOWN_ITEM_VARIANTS;
export const CONTEXT_MENU_DEFAULT_ITEM_VARIANT = DROPDOWN_DEFAULT_ITEM_VARIANT;
export const CONTEXT_MENU_DEFAULT_POSITIONING = {
  ...DROPDOWN_DEFAULT_POSITIONING,
  strategy: "fixed",
} as const satisfies DropdownPositioningOptions;
export const isContextMenuItemVariant = isDropdownItemVariant;
export const resolveContextMenuItemVariant = resolveDropdownItemVariant;

export type {
  DropdownApi as ContextMenuApi,
  DropdownArrowProps as ContextMenuArrowProps,
  DropdownArrowSlots as ContextMenuArrowSlots,
  DropdownCheckboxItemEmits as ContextMenuCheckboxItemEmits,
  DropdownCheckboxItemProps as ContextMenuCheckboxItemProps,
  DropdownCheckboxItemSlots as ContextMenuCheckboxItemSlots,
  DropdownContentProps as ContextMenuContentProps,
  DropdownContentSlots as ContextMenuContentSlots,
  DropdownContextSlots as ContextMenuContextSlots,
  DropdownContextTriggerProps as ContextMenuTriggerProps,
  DropdownContextTriggerSlots as ContextMenuTriggerSlots,
  DropdownContextValue as ContextMenuContextValue,
  DropdownDirection as ContextMenuDirection,
  DropdownEmits as ContextMenuEmits,
  DropdownFocusOutsideEvent as ContextMenuFocusOutsideEvent,
  DropdownGroupProps as ContextMenuGroupProps,
  DropdownGroupSlots as ContextMenuGroupSlots,
  DropdownHighlightChangeDetails as ContextMenuHighlightChangeDetails,
  DropdownInteractOutsideEvent as ContextMenuInteractOutsideEvent,
  DropdownItemContextSlots as ContextMenuItemContextSlots,
  DropdownItemContextValue as ContextMenuItemContextValue,
  DropdownItemEmits as ContextMenuItemEmits,
  DropdownItemIndicatorProps as ContextMenuItemIndicatorProps,
  DropdownItemIndicatorSlots as ContextMenuItemIndicatorSlots,
  DropdownItemProps as ContextMenuItemProps,
  DropdownItemSlots as ContextMenuItemSlots,
  DropdownItemTextProps as ContextMenuItemTextProps,
  DropdownItemTextSlots as ContextMenuItemTextSlots,
  DropdownItemVariant as ContextMenuItemVariant,
  DropdownLabelProps as ContextMenuLabelProps,
  DropdownLabelSlots as ContextMenuLabelSlots,
  DropdownLinkItemEmits as ContextMenuLinkItemEmits,
  DropdownLinkItemProps as ContextMenuLinkItemProps,
  DropdownLinkItemSlots as ContextMenuLinkItemSlots,
  DropdownOpenChangeDetails as ContextMenuOpenChangeDetails,
  DropdownPointerDownOutsideEvent as ContextMenuPointerDownOutsideEvent,
  DropdownPositioningOptions as ContextMenuPositioningOptions,
  DropdownProps as ContextMenuProps,
  DropdownRadioGroupEmits as ContextMenuRadioGroupEmits,
  DropdownRadioGroupProps as ContextMenuRadioGroupProps,
  DropdownRadioGroupSlots as ContextMenuRadioGroupSlots,
  DropdownRadioItemProps as ContextMenuRadioItemProps,
  DropdownRadioItemSlots as ContextMenuRadioItemSlots,
  DropdownRequestDismissEvent as ContextMenuRequestDismissEvent,
  DropdownRootProviderEmits as ContextMenuRootProviderEmits,
  DropdownRootProviderProps as ContextMenuRootProviderProps,
  DropdownRootProviderSlots as ContextMenuRootProviderSlots,
  DropdownRootProps as ContextMenuRootProps,
  DropdownRootSlots as ContextMenuRootSlots,
  DropdownSelectionDetails as ContextMenuSelectionDetails,
  DropdownSeparatorProps as ContextMenuSeparatorProps,
  DropdownSeparatorSlots as ContextMenuSeparatorSlots,
  DropdownSlots as ContextMenuSlots,
  DropdownSubContentProps as ContextMenuSubContentProps,
  DropdownSubContentSlots as ContextMenuSubContentSlots,
  DropdownSubEmits as ContextMenuSubEmits,
  DropdownSubProps as ContextMenuSubProps,
  DropdownSubSlots as ContextMenuSubSlots,
  DropdownSubTriggerProps as ContextMenuSubTriggerProps,
  DropdownSubTriggerSlots as ContextMenuSubTriggerSlots,
  DropdownTriggerValueChangeDetails as ContextMenuTriggerValueChangeDetails,
} from "../dropdown/dropdown";
