export { default as Text } from "./Text.vue";
export {
  KAPPA_TEXT_DEFAULT_VARIANTS,
  KAPPA_TEXT_STYLING,
  KAPPA_TEXT_VARIANTS,
  TEXT_COPY_VARIANTS,
  TEXT_DEFAULT_VARIANTS,
  TEXT_DEPRECATED_HEADING_VARIANTS,
  TEXT_ELEMENTS,
  TEXT_HEADING_VARIANTS,
  TEXT_MONOSPACE_VARIANTS,
  TEXT_SIZES,
  TEXT_VARIANTS,
  isCopyTextVariant,
  isDeprecatedHeadingTextVariant,
  isHeadingTextVariant,
  isMonospaceTextVariant,
  isTextElement,
  isTextSize,
  isTextVariant,
  resolveTextElement,
  resolveTextSize,
  resolveTextSizeClass,
  resolveTextVariant,
  textVariants,
  type KappaTextVariantsProps,
  type TextCopyVariant,
  type TextDeprecatedHeadingVariant,
  type TextElement,
  type TextHeadingVariant,
  type TextMonospaceVariant,
  type TextProps,
  type TextSize,
  type TextSlots,
  type TextVariant,
} from "./text";
